services:
  - type: web
    name: visual-news-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: FLASK_DEBUG
        value: "False"
